[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.5.0",
    "gradio>=6.18.0",
    "ollama>=0.6.2",
    "openai>=2.38.0",
    "pypdf>=6.13.2",
    "python-dotenv>=1.2.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.410",
    "ruff>=0.15.16",
]
